from life_locations import Life_locations
from luck_locations import Lucky_locations
class Board:
    def monopoly(self):
        life_locations = Life_locations
        luck_locatins = Lucky_locations
        monopoly = {
            "0": luck_locatins.lucky_location(),
            "1": 'EAST_COAST1',
            "2": 'EAST_COAST2',
            "3": luck_locatins.lucky_location(),
            "4": 'EAST_COAST3',
            "5": luck_locatins.lucky_location(),
            "6": 'EAST_COAST4',
            "7": life_locations.life_location(),
            "8": 'EAST_COAST5',
            "9": 'RAIL_ROAD1',
            "10": 'FISHING_CORP',
            "11": 'THE_SOUTH1',
            "12": 'THE_SOUTH2',
            "13": luck_locatins.lucky_location(),
            "14": 'THE_SOUTH3',
            "15": luck_locatins.lucky_location(),
            "16": luck_locatins.lucky_location(),
            "17": 'THE_SOUTH4',
            "18": life_locations.life_location(),
            "19": 'THE_SOUTH5',
            "20": 'RAIL_ROAD2',
            "21": 'ENERGY_CORP',
            "22": 'MID_WEST1',
            "23": 'MID_WEST2',
            "24": luck_locatins.lucky_location(),
            "25": 'MID_WEST3',
            "26": luck_locatins.lucky_location(),
            "27": luck_locatins.lucky_location(),
            "28": 'MID_WEST4',
            "29": life_locations.life_location(),
            "30": 'MID_WEST5',
            "31": 'RAIL_ROAD3',
            "32": 'MANUFACTORING_CORP',
            "33": 'WEST_COAST1',
            "34": 'WEST_COAST2',
            "35": luck_locatins.lucky_location(),
            "36": 'WEST_COAST3',
            "37": luck_locatins.lucky_location(),
            "38": 'WEST_COAST4',
            "39": life_locations.life_location(),
            "40": 'WEST_COAST5',
            "41": 'RAIL_ROAD4',
            "42": 'TECH_CORP'
        }