from life_locations import Life_locations
from luck_locations import Lucky_locations
class Board:
    life_locations = Life_locations()
    luck_locations = Lucky_locations()
    monopoly = {
        "0": "GO",
        "1": 'EAST_COAST1',
        "2": 'EAST_COAST2',
        "3": "BEGINNERS_LUCK",
        "4": 'EAST_COAST3',
        "5": "SPEEDING1",
        "6": 'EAST_COAST4',
        "7": "SNOW_STORM",
        "8": 'EAST_COAST5',
        "9": 'RAIL_ROAD1',
        "10": 'FISHING_CORP',
        "11": 'THE_SOUTH1',
        "12": 'THE_SOUTH2',
        "13": "LOTTERY1",
        "14": 'THE_SOUTH3',
        "15": "LOTTERY2",
        "16": "SPEEDING2",
        "17": 'THE_SOUTH4',
        "18": "HURRICANE",
        "19": 'THE_SOUTH5',
        "20": 'RAIL_ROAD2',
        "21": 'ENERGY_CORP',
        "22": 'MID_WEST1',
        "23": 'MID_WEST2',
        "24": "FOR_SALE1",
        "25": 'MID_WEST3',
        "26": "FOR_SALE2",
        "27": "FORECLOSURE1",
        "28": 'MID_WEST4',
        "29": "TORNADO",
        "30": 'MID_WEST5',
        "31": 'RAIL_ROAD3',
        "32": 'MANUFACTORING_CORP',
        "33": 'WEST_COAST1',
        "34": 'WEST_COAST2',
        "35": "SPEEDING3",
        "36": 'WEST_COAST3',
        "37": "FORECLOSURE2",
        "38": 'WEST_COAST4',
        "39": "EARTHQUAKE",
        "40": 'WEST_COAST5',
        "41": 'RAIL_ROAD4',
        "42": 'TECH_CORP'
    }